SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS ADMIN SALT '288ad59460cd4ca8' HASH '4005cfcfcf365a52a46d18ac7fa09d8fedb051f221a8c98157a765152952cf43' ADMIN;        
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;       
CREATE CACHED TABLE PUBLIC."schema_version"(
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL
);    
ALTER TABLE PUBLIC."schema_version" ADD CONSTRAINT PUBLIC."schema_version_pk" PRIMARY KEY("installed_rank");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC."schema_version";        
INSERT INTO PUBLIC."schema_version"("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "installed_on", "execution_time", "success") VALUES
(1, '1', 'create users', 'SQL', 'V1__create_users.sql', 604497932, 'ADMIN', TIMESTAMP '2017-03-11 06:15:45.414', 1, TRUE); 
CREATE INDEX PUBLIC."schema_version_s_idx" ON PUBLIC."schema_version"("success");             
CREATE CACHED TABLE PUBLIC.BLOG(
    ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    USER_ID BIGINT
);             
ALTER TABLE PUBLIC.BLOG ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BLOG;    
CREATE CACHED TABLE PUBLIC.ENTRY(
    ID BIGINT NOT NULL,
    CONTENT CLOB NOT NULL,
    DATE BINARY(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BLOG_ID BIGINT
);              
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ENTRY;   
CREATE CACHED TABLE PUBLIC.ENTRY_TAG(
    ENTRIES_ID BIGINT NOT NULL,
    TAGS_ID BIGINT NOT NULL
);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ENTRY_TAG;               
CREATE CACHED TABLE PUBLIC.TAG(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);  
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;     
CREATE CACHED TABLE PUBLIC.USER(
    ID BIGINT NOT NULL,
    EMAIL VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL
);           
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;    
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_OB8KQYQQGMEFL0ACO34AKDTPE UNIQUE(EMAIL);     
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_EW1HVAM8UWAKNUAELLWHQCHHB UNIQUE(LOGIN);     
ALTER TABLE PUBLIC.ENTRY_TAG ADD CONSTRAINT PUBLIC.FKTP61WE2NJISI24L49L6R4SOQP FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;        
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.FKO476JGPF5V2S40YISJHPYTDLF FOREIGN KEY(BLOG_ID) REFERENCES PUBLIC.BLOG(ID) NOCHECK;           
ALTER TABLE PUBLIC.ENTRY_TAG ADD CONSTRAINT PUBLIC.FK4LIB2ICU7IIYK4S3FRJF54YP4 FOREIGN KEY(ENTRIES_ID) REFERENCES PUBLIC.ENTRY(ID) NOCHECK;   
ALTER TABLE PUBLIC.BLOG ADD CONSTRAINT PUBLIC.FKPXK2JTYSQN41OOP7LVXCP6DQQ FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;            
