CREATE USER IF NOT EXISTS ADMIN SALT '288ad59460cd4ca8' HASH '4005cfcfcf365a52a46d18ac7fa09d8fedb051f221a8c98157a765152952cf43' ADMIN;

CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;

CREATE TABLE PUBLIC.USER(
    ID BIGINT NOT NULL,
    EMAIL VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL
);

CREATE TABLE PUBLIC.TAG(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PUBLIC.ENTRY_TAG(
    ENTRIES_ID BIGINT NOT NULL,
    TAGS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.ENTRY(
    ID BIGINT NOT NULL,
    CONTENT CLOB NOT NULL,
    DATE BINARY(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BLOG_ID BIGINT
);

CREATE TABLE PUBLIC.BLOG(
    ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    USER_ID BIGINT
);

ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.unique_user_email UNIQUE(EMAIL);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.unique_user_login UNIQUE(LOGIN);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.pk_user_id PRIMARY KEY(ID);
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.pk_tag_id PRIMARY KEY(ID);
ALTER TABLE PUBLIC.ENTRY_TAG ADD CONSTRAINT PUBLIC.fk_tag_id FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;
ALTER TABLE PUBLIC.ENTRY_TAG ADD CONSTRAINT PUBLIC.fk_entry_id FOREIGN KEY(ENTRIES_ID) REFERENCES PUBLIC.ENTRY(ID) NOCHECK;
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.fk_blog_id FOREIGN KEY(BLOG_ID) REFERENCES PUBLIC.BLOG(ID) NOCHECK;
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.pk_entry_id PRIMARY KEY(ID);
ALTER TABLE PUBLIC.BLOG ADD CONSTRAINT PUBLIC.fk_user_id FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.BLOG ADD CONSTRAINT PUBLIC.pk_blog_id PRIMARY KEY(ID);