CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;

CREATE TABLE PUBLIC.TAG(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PUBLIC.ENTRY_TAG(
    ENTRIES_ID BIGINT NOT NULL,
    TAGS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.ENTRY(
    ID BIGINT NOT NULL,
    CONTENT CLOB NOT NULL,
    DATE DATETIME NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BLOG_ID BIGINT
);

CREATE TABLE PUBLIC.BLOG(
    ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255) NOT NULL
);

ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.pk_tag_id PRIMARY KEY(ID);
ALTER TABLE PUBLIC.ENTRY_TAG ADD CONSTRAINT PUBLIC.fk_tag_id FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;
ALTER TABLE PUBLIC.ENTRY_TAG ADD CONSTRAINT PUBLIC.fk_entry_id FOREIGN KEY(ENTRIES_ID) REFERENCES PUBLIC.ENTRY(ID) NOCHECK;
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.fk_blog_id FOREIGN KEY(BLOG_ID) REFERENCES PUBLIC.BLOG(ID) NOCHECK;
ALTER TABLE PUBLIC.ENTRY ADD CONSTRAINT PUBLIC.pk_entry_id PRIMARY KEY(ID);
ALTER TABLE PUBLIC.BLOG ADD CONSTRAINT PUBLIC.pk_blog_id PRIMARY KEY(ID);